branches:
  only:
  - master
  - stable
language: java
jdk:
  - openjdk11
install: "/bin/true"
script:
  - "./cd/test.sh"
env:
  global:
  - secure: mo2w1qqkT9Pcu3rd51WL/ZaJZNaj2stfHP39zx06I55+dt76D/XCc50Iw/GrZ+kL4pxDYlQq0aSi6ExQg7AruJE/rhtDxr+csprwcVO5KloG203f2FzdkqHr5wiBShL1N7B66/7WGsCgwGB5Y8HOaxz2N43rPi3QnqMItTfazS1z6uldqt9/6FhdRs1fHOkxL8x5aBZ4b4tqJf1f3izzF2uc7FxQPdR95k6VW3yYtM5dLCT/CH9rVqXk0mnETlqBG/Y2qYdN7gOh18d9wvgyhaBraR/+RDEipPb5GD1u/L4jBsCqXIsLKNFpatXeC9bAav3EQUjBnO5CMQ/WCwPcnhKM3EvTxVn+oHo0EgzOGiIy5C9aSYknuxOjV2w6Yr3rsEU0K5SAmmYSX9XFmiCBGNu3AOcbDmSE1HMS6ICqMoGT6OzI8tLlscL/7G2MzzPavw0h6IQ/bK81MSxzmmTi+EccN5WtLrgy7jlvIHRxwrOVTkb5eTnSyisi+EoDk7hyvt9ar0hWRU2MDufKXUxPlQXLV/mCb0ldjB/2/Ta6lCpe/eLLhHowsdehsMhkuEwJJyR85Js14LKKYDrthI7YUmQc0CXyGt4fR+FoJdYips5QuZAfl0COMbSL6Il8sr3JwTyQF1746r8XoPeT+40xsx6/cPEGQsNEvNtBbAuKe5g=
  - secure: qBc3bvhnWPEUNBm/GJffWuA0PEoxObujTtL/jybty+s0uxSyH68/OwaeMtia3QwZUqoskaiqvZlZ7Cz3b2CGYYsBpaDhg9DL1lh5qe5AmbSOlXg/7JXmgDZ5Q9RHt8jFLvHzrxelkVTGOxOXkEAw8Dhn7PNqFCGqM1rugUltR9CADiHSZ6FrUSL9c2PUt3Ac9TQcLoMQj8HZMgjBnrXc5ygydllIPFgjD5KMG4vr4NvtEpSAC2cb0JCGNvL8kUW0vAivVP6fMHAiEDUcCs/V3JVCBk7u/RsACpi6u/PWZmfBwEnHG1Mvxc6UQcEtDhqPBZlw6ia+WsTS4cmG9Zh4KzMg3tOeLO6tQc/05sAsJBvuOV26bMH5muHNb5689s42awIgcogFMameaXUN56DZw8QqjZC5kfPZqaSckobYn7GCdeCP5On/4iIHjJd7PzoWdk1JsNhtF9aFVonBm1sM6tnvtt4RspW/3AWeu3zQkNfO4lZuw4l1Wd5gu1X9FWgZxU1GjOQ6pRZk/+yMcJmffqX9B3dSRh6l3lNt8Wms5iZz7yGlf47FZ41PCMDaPivJLv7Yh8wuhRqBt/j9dM/dzBS2GaDvL+ZuNBQQlzwaxYP9IgM76UGwtIT/+zwQHSPutZaRDBUEJ8nI9TXmHzdrwBV68ZCNMkR3CHnBrcTJvzQ=
  - secure: sLbGqfN2dWt9NNGS/hYtf9Hscynp0ylXo7yfl68AtKhMqZVOFw6wuzfdev4wyslgKlg4qskM5Eqa6SSR2Cu3FStpNlWaLHmgsvq2WcS9nWejJRXrEAJ3GSYStQoWzUikv8Rajmd3WTgj95jaxDy91eupoLd4vm/ViGAl7TdqoBureowP7AgOjg+n83hTpDeVXKC3k4/4D055pbV67zxlwgB16DyObWkWPLdWLgdLPOlH2w5v/nSSLGGmPjDi36S5+G2sLpzwwSuP8Q/SNoOhouHBQ4Hl8SXylEI/I9kbyU4QZvn7qAZPGysqH80vpTOPbOLBr/wAvrhYDQ2KIvYhfy+4nV1gfUoel2GpsZ3dpi7GlJi2PuxDJ1Kb+8ZcO1qfcgsbag7avdZP0639kVb7Ng2GV8VjMxnuqFvizZIbpBhLN77X00DKakTgBbdDaRxEMkShdzZcPbmjRyRqn7hQe4eXNfhtcS9XlRsED2EiFyuBrnkvKWbhes7HD8ZH57j4k3BX/QwuO8NwZI7pP3LZId0Txu7kPHoHmtb21wsQBIEOUdqfNWK5thq9WiFnN3tdjrIWzZmWJQvL2IcgUbKwrKRk0EHYADDKEUn2bg0noGNymDmV9f4Xd5cTiS+qIWjiQFsj1HL0C/bE3yKvqIBSL7ltf7D/lisiAiZmBqapsSg=
  - secure: WDVnPibXqWZucAfBZZ0BVD2KWGQbzqq5njO0N5hPKOugQxnyZRKv04Nlhq0JzF3MNzD7rHfesjKwccsxV2pIAAzbZ8NwjYTntKURlSuOK9/zRxzAVWS40r/EdDteBhnFea6TCRLbBqvEwjkiS4I+6pU5Qzdgv68jCW613eQ3gA2OsCb6w0IscJ9ojY50QHbnLHoDVzDi/M8SOvWylkBZ/9mWFfrtcTcUf7ygVLTyQtashtxqj9/KmgbrBwtp3FCQ+LiZ0scA6TjD8K8LB/EFJJwLAIHch8Pum+Gt8rVy2zAODILYwwuVUJbKJDP59aQmMWz6dOOcpfiUL5tuwxuVDuFRVaoxQEzACXpPsbjRKcb45+WpnBSrg6sZYs6urBP1ylHNpo3D68z9BYwCIkLtn+azLNquM/wfruQScldiY/gDS4rEu0flo1Vs6yuiUSetf401wJ/TwFPUKdkpAj7gnsJsfGMOob/64NHpmDgGCH1rrw6Kk5d2I22bC6ZCU+8gYxjXwh1v1Wc7lm5TuHtwilgImb+k+Ic0OYh5NvJKmzU7id/gqILwRzkbiY8OpIQjk15iknhGyvLJz10KlBJjH8YxoXJNlzoz1KT1+xe2lwaSAq9ve1WZwASN8Dj3TDmwGK9/C51WmIMDr3vYCM5iUTtRjKmazcJDD9wlmNGdW8Y=
before_deploy:
  - openssl aes-256-cbc -K $encrypted_c7d28ed8a9a3_key -iv $encrypted_c7d28ed8a9a3_iv
    -in cd/codesigning.gpg.enc -out cd/codesigning.gpg -d
deploy:
  -
    skip_cleanup: true
    provider: script
    script: "./cd/deploy.sh"
    on:
      branch: master
