name: Publish Maven Package

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
          cache: maven
          server-id: ossrh
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_KEY_NAME }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: ⭐ Publish to Apache Maven Central ⭐
        run: mvn deploy -P publish -DskipTests=true
