name: Publish Maven Package

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
          cache: maven
          server-id: ossrh
          server-username: MAVEN_USERNAME #env variable for username in deploy
          server-password: MAVEN_PASSWORD #env variable for password in deploy
          gpg-private-key: MAVEN_GPG_PRIVATE_KEY #env variable for GPG private key
          gpg-passphrase: MAVEN_GPG_PASSPHRASE #env variable for GPG private key passphrase
      - name: ⭐ Publish to Apache Maven Central ⭐
        run: mvn deploy --batch-mode -P publish -DskipTests=true
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
